# deployment.yaml is the manifest file that will be used to create the deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loginapp
  name: {{ .Release.Name }}-loginapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: sample
      # imagePullSecrets:
      # - name: helm-secret 
# strategy:
#   type: RollingUpdate
#   rollingUpdate:
#     maxUnavailable: 1   # Only 1 pod will be down at a time during the update
#     maxSurge: 1         # 1 extra pod will be created while updating
