name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/jmuachifi/loginapp:${{ github.sha }} .
          docker push docker.io/jmuachifi/loginapp:${{ github.sha }}

  update_helm_chart:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git remote URL with PAT
        run: |
          git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/login-app-argocd.git

      - name: Configure Git user information
        run: |
          git config --global user.email "jmuachifi@gmail.com"
          git config --global user.name "Jodionisio Muachifi"

      - name: Update Helm chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/g" manifests/values.yaml
          git add manifests/values.yaml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push origin HEAD:main

  deploy_to_argocd:
    runs-on: ubuntu-latest
    needs: update_helm_chart
    steps:
      - name: Trigger ArgoCD Sync
        run: |
          # Ensure `argocd` CLI is installed
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/latest/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
  
          # Log into ArgoCD using secrets
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure --timeout 60
  
          # Sync ArgoCD application
          argocd app sync login-app-argocd
